name: CI Formatting and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    name: Format and lint python files, repository.yaml, and repo folder structure
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install dependencies from pyproject.toml
        run: uv pip install .[dev]

      - name: Check if linted with ruff
        run: uvx ruff check --extend-select I -show-fixes --diff

      - name: Check if formatted with ruff
        run: uvx ruff format --check --diff

      - name: Lint repository.yaml and check repo folder structure
        run: uvx pytest tests/test_repository_yaml.py tests/test_repo_folder_structure.py -v