name: ZLFLO Data linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint python files, repository.yaml, and repo folder structure
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: ruff-lint
        uses: chartboost/ruff-action@v1

      - name: ruff-format
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

      - name: Lint repository.yaml and check repo folder structure
        run: uv run pytest tests/test_repository_yaml.py tests/test_repo_folder_structure.py -v